/*   Messages related to the GUI library.
/*
msg button_abort
  lan english -def
    Abort
msg button_continue
  lan english -def
    Continue
msg button_done
  lan english -def
    Done
msg button_no
  lan english -def
    No
msg button_ok
  lan english -def
    OK
msg button_yes
  lan english -def
    Yes
msg err_enter_fp
  lan english -def
    Not a floating point value, try again.
msg err_enter_int
  lan english -def
    Not an integer value, try again.
